---
- name: Install base packages
  package: name=tmux state=present
  become: true
- include: files.yml
- name: Install xpane
  shell: wget https://raw.githubusercontent.com/greymd/tmux-xpanes/master/bin/xpanes -O /usr/local/bin/xpane
  become: true
- file:
    path: /usr/local/bin/xpane
    mode: 0755
  become: true
- name: Install Tmux Plugin Manager
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm force=yes
- name: Install plugins
  shell: ~/.tmux/plugins/tpm/bin/install_plugins
  environment:
    TMUX_PLUGIN_MANAGER_PATH: ~/.tmux/plugins/

