---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: vagrant-ubuntu
    box: ubuntu/bionic64
    memory: 1024
    cpus: 1
    provider_raw_config_args:
      # https://github.com/ansible/molecule/issues/1556
      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
  - name: vagrant-fedora
    box: fedora/29-cloud-base
    memory: 1024
    cpus: 2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    # - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint:
    name: flake8
  options:
    # show which tests where executed in test output
    v: 3
