---
- name: Install zsh
  package:
    name=zsh
    state=present
    update_cache=yes
  become: yes
- name: Install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh force=yes
- name: Back up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.bak ; fi
- name: Copy my .zshrc
  copy: src=zshrc dest=~/.oh-my-zsh/templates/zshrc.zsh-template
- name: Creating new ~/.zshrc
  file: src=~/.oh-my-zsh/templates/zshrc.zsh-template dest=~/.zshrc state=link
- name: Copy my .zsh_nocorrect
  copy: src=zsh_nocorrect dest=~/.zsh_nocorrect
- name: Get zsh path
  command: which zsh
  register: zsh_path
- name: Switch to zsh
  command: chsh -s {{ zsh_path.stdout }}
